import HeaderComponent from "@/components/HeaderComponent"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
					<HeaderComponent/>
				</header>
        {children}
      </body>
    </html>
  )
}
